source "http://rubygems.org/"
gem "rails", "2.3.5"
gem "i18n", "0.4.2"
gem "georuby", "2.0.0"
gem "yahoo-geoplanet"
#gem "elecnix-ruby-geonames"
gem "oauth"
gem "pg","0.15.1"
gem "fastthread"
gem "simple-rss"
gem "libxml-ruby"
gem "nokogiri", "1.5.5"
gem "rake", "0.9.2.2"
gem "fastercsv"
gem "rmagick"
gem "json"